### ISSUE TITLE
Call to undefined function josegonzalez\Queuesadilla\Worker\pcntl_signal()

### ISSUE THREAD

**Issue by FinlayDaG33k** [josegonzalez/cakephp-queuesadilla#32]
Hii there,

I'm currently trying to setup this plugin, but I'm getting the error in the title when I try to run the `cake queuesadilla` command.  
I have tried following the guide [here](https://cakephp-queuesadilla.readthedocs.io/).

Any clue how to solve it?

UPDATE: forgot the stacktrace:
```
Stack Trace:
#0 /var/www/vendor/josegonzalez/cakephp-queuesadilla/src/Shell/QueuesadillaShell.php(58): josegonzalez\Queuesadilla\Worker\SequentialWorker->__construct(Object(josegonzalez\Queuesadilla\Engine\MysqlEngine), Object(Cake\Log\Engine\ConsoleLog), Array)
#1 /var/www/vendor/josegonzalez/cakephp-queuesadilla/src/Shell/QueuesadillaShell.php(21): Josegonzalez\CakeQueuesadilla\Shell\QueuesadillaShell->getWorker(Object(josegonzalez\Queuesadilla\Engine\MysqlEngine), Object(Cake\Log\Engine\ConsoleLog))
#2 /var/www/vendor/cakephp/cakephp/src/Console/Shell.php(532): Josegonzalez\CakeQueuesadilla\Shell\QueuesadillaShell->main()
#3 /var/www/vendor/cakephp/cakephp/src/Console/CommandRunner.php(371): Cake\Console\Shell->runCommand(Array, true)
#4 /var/www/vendor/cakephp/cakephp/src/Console/CommandRunner.php(166): Cake\Console\CommandRunner->runShell(Object(Josegonzalez\CakeQueuesadilla\Shell\QueuesadillaShell), Array)
#5 /var/www/bin/cake.php(12): Cake\Console\CommandRunner->run(Array)
#6 {main}
```

**Comment by cleptric** [comment]
You have to install the php `pcntl` extension

**Comment by FinlayDaG33k** [comment]
Oof, I thought I already done that... but apparently I didn't... Will report back!

**Comment by josegonzalez** [comment]
Should that be in the composer.json somehow?

**Comment by cleptric** [comment]
@josegonzalez Yes, this would make it more obvious for sure :)

**Comment by josegonzalez** [comment]
@cleptric PR welcome!
